// <auto-generated />
using System;
using EcoRecyclersGreenTech.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoRecyclersGreenTech.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Orders.AuctionOrder", b =>
                {
                    b.Property<int>("AuctionOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionOrderID"));

                    b.Property<int>("AuctionStoreID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WinnerID")
                        .HasColumnType("int");

                    b.HasKey("AuctionOrderID");

                    b.HasIndex("AuctionStoreID");

                    b.HasIndex("WinnerID");

                    b.ToTable("AuctionOrders");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Orders.JobOrder", b =>
                {
                    b.Property<int>("JobOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobOrderID"));

                    b.Property<int>("JobStoreID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Meetingdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("JobOrderID");

                    b.HasIndex("JobStoreID");

                    b.HasIndex("UserID");

                    b.ToTable("JobOrders");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Orders.MachineOrder", b =>
                {
                    b.Property<int>("MachineOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineOrderID"));

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuyerID")
                        .HasColumnType("int");

                    b.Property<int>("MachineStoreID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MachineOrderID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("MachineStoreID");

                    b.ToTable("MachineOrders");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Orders.MaterialOrder", b =>
                {
                    b.Property<int>("MaterialOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialOrderID"));

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuyerID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialStoreID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialOrderID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("MaterialStoreID");

                    b.ToTable("MaterialOrders");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Orders.RentalOrder", b =>
                {
                    b.Property<int>("RentalOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalOrderID"));

                    b.Property<int>("BuyerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentalStoreID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RentalOrderID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("RentalStoreID");

                    b.ToTable("RentalOrders");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Settings.ChatUser", b =>
                {
                    b.Property<int>("ChatUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatUserID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("To")
                        .HasColumnType("int");

                    b.HasKey("ChatUserID");

                    b.HasIndex("From");

                    b.HasIndex("To");

                    b.ToTable("ChatUsers");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Settings.Complaint", b =>
                {
                    b.Property<int>("ComplaintID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCounter")
                        .HasColumnType("int");

                    b.HasKey("ComplaintID");

                    b.HasIndex("From");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Settings.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("To")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID");

                    b.HasIndex("From");

                    b.HasIndex("To");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Stores.AuctionStore", b =>
                {
                    b.Property<int>("AuctionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionID"));

                    b.Property<DateTime>("AuctionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SellerID")
                        .HasColumnType("int");

                    b.Property<decimal>("StartPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AuctionID");

                    b.HasIndex("SellerID");

                    b.ToTable("AuctionStores");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Stores.JobStore", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkHours")
                        .HasColumnType("int");

                    b.HasKey("JobID");

                    b.HasIndex("PostedBy");

                    b.ToTable("JobStores");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Stores.MachineStore", b =>
                {
                    b.Property<int>("MachineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineID"));

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SellerID")
                        .HasColumnType("int");

                    b.HasKey("MachineID");

                    b.HasIndex("SellerID");

                    b.ToTable("MachineStores");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Stores.MaterialStore", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SellerID")
                        .HasColumnType("int");

                    b.HasKey("MaterialID");

                    b.HasIndex("SellerID");

                    b.ToTable("MaterialStores");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Stores.RentalStore", b =>
                {
                    b.Property<int>("RentalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalID"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime>("AvailableFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerMonth")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RentalID");

                    b.HasIndex("OwnerID");

                    b.ToTable("RentalStores");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Users.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("AdminType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Users.Craftsman", b =>
                {
                    b.Property<int>("CraftsmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CraftsmanID"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("SkillType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CraftsmanID");

                    b.ToTable("Craftsmen");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Users.Factory", b =>
                {
                    b.Property<int>("FactoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactoryID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactoryImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactoryType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FactoryID");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Users.Individual", b =>
                {
                    b.Property<int>("IndividualID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndividualID"));

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndividualID");

                    b.ToTable("Individuals");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Users.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Locaton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserProfieImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("UserTypeID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Users.UserType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeID"));

                    b.Property<int?>("RealTypeID")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeID");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Orders.AuctionOrder", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Stores.AuctionStore", "AuctionStore")
                        .WithMany()
                        .HasForeignKey("AuctionStoreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionStore");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Orders.JobOrder", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Stores.JobStore", "JobStore")
                        .WithMany()
                        .HasForeignKey("JobStoreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobStore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Orders.MachineOrder", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoRecyclersGreenTech.Data.Stores.MachineStore", "MachineStore")
                        .WithMany()
                        .HasForeignKey("MachineStoreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("MachineStore");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Orders.MaterialOrder", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoRecyclersGreenTech.Data.Stores.MaterialStore", "MaterialStore")
                        .WithMany()
                        .HasForeignKey("MaterialStoreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("MaterialStore");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Orders.RentalOrder", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoRecyclersGreenTech.Data.Stores.RentalStore", "RentalStore")
                        .WithMany()
                        .HasForeignKey("RentalStoreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("RentalStore");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Settings.ChatUser", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("From")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("To")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Settings.Complaint", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("From")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Settings.Feedback", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("From")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("To")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Stores.AuctionStore", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Stores.JobStore", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("PostedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Stores.MachineStore", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Stores.MaterialStore", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Stores.RentalStore", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Users.User", b =>
                {
                    b.HasOne("EcoRecyclersGreenTech.Data.Users.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("EcoRecyclersGreenTech.Data.Users.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
